### ISSUE TITLE
Multiple locks, which one is which

### ISSUE THREAD

**Issue by nutteloost** [cpolhout/loqed_custom_component#11]
I installed the integration via HACS and I would like to add my Loqed locks. I have two. Both are auto discovered, but how do I know which one is which?

![2E752FAE-0A74-4983-8F74-5703BCAA2C05](https://user-images.githubusercontent.com/31592734/211093759-0b0ab715-996c-4478-b5d9-7477915609fd.jpeg)

**Comment by nutteloost** [comment]
Removed one Bridge from power source and restarted Home Assistant so I knew which lock I should configure first.

After configuring, the locks are still auto discovered. Whenever I ignore the auto discovered locks, the configured lock is removed from the integration…

**Comment by HFeenstra** [comment]
Why is this case closed? I still have the exact same issue. Once I remove the New discovered Loqed, since I have already one, my current correct working Loqed is removed as well. 
What means I have to start over again…?
